name: run-tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.4]
        laravel: [12.*]
        stability: [stable]
        include:
          - laravel: 12.*
            testbench: 9.*
        exclude:
          - laravel: 12.*
            php: 8.4

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      # Checkout the package code.
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      # Cache dependencies and build outputs to improve workflow execution time.
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      # Setup PHP and extensions.
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: xdebug

      # Install the package dependencies.
      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nesbot/carbon:>=2.62.1" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      # Execute the test suite for Laravel.
      - name: Execute Laravel tests
        run: php artisan test

      # Upload code coverage to Scrutinizer CI, only for specific version.
      - name: Upload coverage to scrutinizer-ci
        if: matrix.php == '8.4' && matrix.laravel == '12.*' && matrix.stability == 'prefer-stable'
        run: |
          composer require scrutinizer/ocular
          cp phpunit.xml.dist phpunit.xml
          vendor/bin/phpunit --migrate-configuration
          vendor/bin/phpunit --testsuite Laravel --coverage-clover=coverage.clover
          vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
